#ifndef PIN_H
#define PIN_H 1

#define LEFT_MOTOR_ESC 23
#define LEFT_MOTOR_RELAIS 17
#define RIGHT_MOTOR_ESC 22
#define RIGHT_MOTOR_RELAIS 27

#define LEFT_RUDDER_SERVO 18
#define RIGHT_RUDDER_SERVO 25
#define TOP_RUDDER_SERVO 24

#endif /* PIN_H */