all:

clean:
	#add missing subfolders
	#$(MAKE) -C gpio/ clean
	#$(MAKE) -C mpu6050/ clean
	#$(MAKE) -C ads1115/ clean
	#$(MAKE) -C bmp280/ clean
	#$(MAKE) -C qmc5883l/ clean
	#$(MAKE) -C neo6m/ clean
	$(MAKE) -C motor/ clean
	$(MAKE) -C servo/ clean
	rm -f *.elf